### ISSUE TITLE
TypeError: this.body.readBigInt64BE is not a function

### ISSUE THREAD

**Issue by vcombey** [janakj/pulseaudio.js#1] opened 2021-08-08 17:45 UTC
when trying the exemple on the wiki I got  TypeError: this.body.readBigInt64BE is not a function
at ``` const stream = await pa.createRecordStream({
    sampleSpec : { rate, format, channels }
});```
after connect
(node:66325) UnhandledPromiseRejectionWarning: TypeError: this.body.readBigInt64BE is not a function
    at Command.TagStruct.getUsec (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/packet.js:223:28)
    at CreateRecordStream.processResponse (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/command.js:818:45)
    at PulseAudio.<anonymous> (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/client.js:700:54)
    at step (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/client.js:61:23)
    at Object.next (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/client.js:42:53)
    at fulfilled (/home/vcombey/record_audio_linux/node_modules/pulseaudio.js/dist/client.js:33:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:66325) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66325) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by janakj** [comment] 2021-08-21 23:50
Could you, please, let me know your NodeJS version?

It is strange that you are getting this error because, according to the documentation, the method should exist since NodeJS v12.0.0 or v10.20.0: https://nodejs.org/api/buffer.html#buffer_buf_readbigint64be_offset

**Comment by janakj** [comment] 2022-04-30 05:12
Cannot reproduce. Closing.

**Closed as completed by janakj** 2022-04-30 05:12 UTC
